services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SHORTCUT_SECRET
        sync: false
